server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:../application-db.yml
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customer/profile/**
        - id: product-service-customer
          uri: http://localhost:8083
          predicates:
            - Path=/customer/products/**
        - id: product-service-agent
          uri: http://localhost:8083
          predicates:
            - Path=/agent/products/**
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/customer/cart/**
        - id: order-service-customer
          uri: http://localhost:8085
          predicates:
            - Path=/customer/orders/**
        - id: order-service-agent
          uri: http://localhost:8085
          predicates:
            - Path=/agent/orders/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/customer/payments/**
        - id: batch-service
          uri: http://localhost:8087
          predicates:
            - Path=/agent/batch/**
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${app.jwt.secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
